- name: nginx install
  ansible.builtin.dnf:
    name: nginx
    state: installed
    
- name: starting the nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: run app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

#if there is change in configuration only then we need to do restart
- name: copy the conf file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify: 
  - Restart Nginx Service 

#handlers are notifier when there is change in conf then notify to restart the nginx service
#- name: Restart Nginx Service 
#  ansible.builtin.service:
#    name: nginx
#    state: restarted